server:
  port: 8000
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  mvc:
    dateFormat: yyyy-MM-dd HH:mm:ss

  #thymeleaf start
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
  #thymeleaf end
  servlet:
    multipart:
      enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.lixiangshequ.entity.base
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring.output.ansi.enabled: always

logging.level:
  lixiangshequ:
    repository:
      UserMapper: DEBUG
  org:
    springframework:
      security: info
      boot:
        autoconfigure: ERROR

debug: true

